safe: true
lsi: false
pygments: true

permalink: /:year-:month-:day-:title.html

title: mobile.cologne
tagline: user group for ios, android, html5 & co.
author:
  name: mobile.cologne
  email: spam@mobilecologne.de

production_url : http://www.mobilecologne.de

